spring.application.name=Hospital-Management-UI
server.port= 8095

backend.api.url=http://localhost:8091/api
spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html
#spring.thymeleaf.cache=false

